# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'sinatra'
gem 'sinatra-contrib'
gem "puma"
gem 'sinatra-cross_origin', '~> 0.4.0'